### ISSUE TITLE
Allow pull request reporting with pull_request_target

### ISSUE THREAD

**Issue by noisymime** [arduino/report-size-deltas#109]
### Describe the request

I've been trying to implement report-size-deltas on my repo and have it produce reports into PRs as they are submitted and prior to them being merged. This was working fine within my local fork, however I could not get it to work once this was committed to the main organisation repository. 

The initial issue was that, despite allowing `permissions: write-all` on the workflow, the script received 403 permission errors when trying to make the comment. It turns out that PRs from public forks that are not made by a project contributor will always have their workflow permissions lowered to `read`, which is what caused the comment to fail (Write permission on contents and pull-requests is required). 

This is enforced by Github and there are no settings available to change this. The only mechanism to allow these permissions for a public PR (Without having to use a custom Github App) are to use the `pull_request_target` event rather than `pull_request`. Per the Github documentation for `pull_request_target`: 

> This event runs in the context of the base of the pull request, rather than in the context of the merge commit, as the pull_request event does. 

Thus its write permissions will not get overwritten. I have confirmed that running the workflow with a trigger of `pull_request_target`results in the correct permissions and no more 403 errors. 

However, there are multiple places within `reportsizedeltas.py` (and `compilesketches.py`) that explicitly look for an Github event_name of `pull_request` rather than `pull_request_target` meaning that the comment on the PR does not work. 

Would it be possible for these scripts to look for either of these options rather than `pull_request` only?  I understand that this is something of a large ask so feel free to close, but currently there appears to be no other way to allow public PRs to an organisation to trigger these reports as far as I can see. 

### Describe the current behavior

Modify a workflow so that it runs on the `pull_request_target` event rather than `pull_request`. 

### 'arduino/report-size-deltas' version

1.1

### Issue checklist

- [X] I searched for previous requests in [the issue tracker](https://github.com/arduino/report-size-deltas/issues?q=)
- [X] I verified the feature was still missing when using the latest version
- [X] My request contains all necessary details

**Comment by per1234** [comment]
Hi @noisymime. At the time GitHub added the [`pull_request_target` event](https://docs.github.com/en/actions/writing-workflows/choosing-when-your-workflow-runs/events-that-trigger-workflows#pull_request_target) trigger support to GitHub Actions, I also had hopes that this might provide a way to use the action on-demand . However, after investigation I found that it is not possible.

The **arduino/report-size-deltas** action relies on the availability of the [report data](https://github.com/arduino/compile-sketches#enable-deltas-report) that is generated by the [**arduino/compile-sketches** action](https://github.com/arduino/compile-sketches). This means that the **arduino/report-size-deltas** action must be triggered after that action has run (not in a workflow running simultaneously).

Access to the report can be accomplished by running the **arduino/report-size-deltas** from the same workflow as the **arduino/compile-sketches** action (which is already supported and [the recommended approach for private repositories](https://github.com/arduino/report-size-deltas#run-from-the-same-workflow-as-the-arduinocompile-sketches-action)). However, the `pull_request_target` event can not be used as the workflow run trigger in this case because that would cause the [**actions/checkout**](https://github.com/actions/checkout) action to check out the repo to the _**base ref**_ of the pull request instead of the _**head ref**_, and it is essential for the sketch compilations to be done on the contents at the head ref. It is possible to configure a `pull_request_target`-triggered workflow to checkout the head ref, but [that would make the workflow a serious security vulnerability in a public repository](https://securitylab.github.com/research/github-actions-preventing-pwn-requests/).

So the `pull_request_target` event is a dead end.

A different event was added more recently (it was not available at the time this action was written):

https://docs.github.com/en/actions/writing-workflows/choosing-when-your-workflow-runs/events-that-trigger-workflows#workflow_run

> This event occurs when a workflow run is requested or completed. It allows you to execute a workflow based on execution or completion of another workflow.

I think this one is the real solution for running the **arduino/report-size-deltas** on demand in public repositories. It can be triggered on completion of the workflow that runs the **arduino/compile-sketches** action, and the workflow triggered by this event will have the necessary permissions to make the report comment:

> The workflow started by the `workflow_run` event is able to access secrets and write tokens, even if the previous workflow was not. This is useful in cases where the previous workflow is intentionally not privileged, but you need to take a privileged action in a later workflow.

Migrating from the `schedule` event triggered approach to the `workflow_run` event triggered approach is something I would like to do, but the reality is that resources are not available for working on beneficial but non-critical improvements like this. So I don't know when or if such work will ever happen. A pull request for such work is welcome, but resources are also unavailable for reviewing such pull requests so it is likely that it would not be merged any time soon (but users who want that functionality would be welcome to switching to using the fork from which the PR was staged in their workflows, so it would still be useful to the community even before it was merged).

---

All that said, please note that, although what you are trying to do is better from an efficiency standpoint, it is unnecessary. For this use case, the action is designed to be used in a workflow that is triggered periodically by [a `schedule` event](https://docs.github.com/en/actions/writing-workflows/choosing-when-your-workflow-runs/events-that-trigger-workflows#schedule). The action will then comment reports to any pull request that doesn't already have one. The `schedule` event trigger allows the workflow to have the permissions it needs to make the comment.

The action has been used this way in hundreds of public repositories for years, successfully making deltas reports on thousands of pull requests submitted from forks.

We provide the workflow content in the documentation here:

https://github.com/arduino/report-size-deltas#scheduled-workflow

You can just copy and paste that into your workflow and you are done!
