### ISSUE TITLE
Artifacts not detected in pull requests for scheduled run

### ISSUE THREAD

**Issue by forntoh** [arduino/report-size-deltas#112]
### Describe the problem

Artifacts not detected in pull requests for scheduled run

### To reproduce

Here is the branch run, you can see the artifact attached for PR 199

https://github.com/forntoh/LcdMenu/pull/199/checks

`Compile Examples` completed and an artifact was uploaded

However, I get the following message when I rerun the workflow with debug, it seems like it isn't able to read the artifacts from the PR

https://github.com/forntoh/LcdMenu/actions/runs/10919817940/job/30309315191

### Expected behavior

It should detect the attached artifacts

### 'arduino/report-size-deltas' version

v1

### Issue checklist

- [X] I searched for previous reports in [the issue tracker](https://github.com/arduino/report-size-deltas/issues?q=)
- [X] I verified the problem still occurs when using the latest version
- [X] My report contains all necessary details

**Comment by forntoh** [comment]
@2bndy5 Do you by any chance know why this action doesn't detect the artifacts on my repo?

**Comment by 2bndy5** [comment]
Looking at the workflow run logs, I see a single error:
> Compiling previous version of sketch to determine memory usage change
Compiling sketch: examples/KeyboardAdapter
Compilation failed

This is likely because the examples/KeyboardAdapter is new and no previous version exists.

As for the "no artifact found", you need to download the artifacts you uploaded in the other CI job. I don't see this step performed in your workflow. See the [FAQ for an example](https://github.com/arduino/report-size-deltas/blob/main/docs/FAQ.md#workflow-triggered-by-pull_request-event).

**Comment by 2bndy5** [comment]
Oh, I see you copied the [cronjob example from the FAQ](https://github.com/arduino/report-size-deltas/blob/main/docs/FAQ.md#size-deltas-report-workflow) doc. I think that example is erroneous, but I could be wrong. I'm not this repo's author.
